### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [AngelesMB/listado-adalabers#1]
Excelente trabajo @AngelesMB  !

### Algunas sugerencias para mejorarlo:

- [x] Muestra el mensaje de error en algún elemento de `html`, por ejemplo puedes implementar un modal. El uso de los alert, prompt y confirm son creados por el navegador y sus estilos visuales dependen enteramente de éste, es recomendable que controles los mensajes desde tu componente: https://github.com/Adalab/modulo-3-evaluacion-intermedia-AngelesMB/blob/a98ceb5f19878d757adaa9eac333127abc490a25/src/components/App.js#L55 

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by igarrido-adalab** [comment]
Perfecto! Puedes cerrar el Issue
